apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsample-debug
  labels:
    app.kubernetes.io/name: tsample-debug
    app: tsample-debug
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tsample-debug
      app: tsample-debug
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tsample-debug
        app: tsample-debug
    spec:
      containers:
        - name: tsapp
          image: "dukecyber/ts-log-generator:latest"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8080